### ISSUE TITLE
Unab

### ISSUE THREAD

**Issue by sidwagle** [neo4j-contrib/gremlin-plugin#40]
Neo4j version = 3.0.4
JDK = 8 build 60

I have recompiled source with neo4j version 3.0.4 and fixed all compile time errors.

When trying to enable plugin with Neo4j, the server fails with this error trace:

2016-08-31 03:22:36.139+0000 INFO  Mounted unmanaged extension [org.neo4j.server.plugin.gremlin] at [/ext]
2016-08-31 03:22:36.475+0000 ERROR The ResourceConfig instance does not contain any root resource classes.
2016-08-31 03:22:36.475+0000 WARN  unavailable The ResourceConfig instance does not contain any root resource classes.
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)

..................

2016-08-31 03:22:36.476+0000 WARN  FAILED o.e.j.s.ServletContextHandler@1b20c1ca{/ext,null,STARTING}: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-7e2cb4dd@da352b65==org.neo4j.server.web.NeoServletContainer,-1,false org.neo4j.server.web.NeoServletContainer-7e2cb4dd@da352b65==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-7e2cb4dd@da352b65==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)

**Comment by jexp** [comment]
Did you also upgrade the jersey and other versions? Feel free tobsend a PR witj your changes. 

Von meinem iPhone gesendet
